version: '3'
services:
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
  seq:
    image: "datalust/seq"
    ports:
      - "8080:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
